"""HTTP entrypoint for the GridWise submission service."""

import logging

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from .interpretation import GeminiDirectiveInterpreter, LLMInterpretationError
from .optimizer import OptimizationError, optimize_energy_schedule
from .replay_validator import PlanValidationError, validate_solved_plan
from .schemas import (
    OptimizeEnergyRequest,
    OptimizeEnergyResponse,
)


logger = logging.getLogger(__name__)

app = FastAPI(
    title="GridWise Energy Optimizer",
    version="1.0.0",
)


@app.exception_handler(RequestValidationError)
async def handle_request_validation_error(
    _request: Request, exc: RequestValidationError
) -> JSONResponse:
    """Use the official 400/422 distinction without exposing stack traces."""
    malformed_json = any(error.get("type") == "json_invalid" for error in exc.errors())
    if malformed_json:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"detail": "malformed JSON request body"},
        )
    return JSONResponse(
        status_code=422,
        content={"detail": jsonable_encoder(exc.errors())},
    )


@app.exception_handler(PlanValidationError)
async def handle_plan_validation_error(
    _request: Request, _exc: PlanValidationError
) -> JSONResponse:
    """Never expose an invalid replayed plan or internal solver diagnostics."""
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "optimization plan validation failed"},
    )


@app.exception_handler(Exception)
async def handle_unexpected_error(request: Request, _exc: Exception) -> JSONResponse:
    """Return a safe generic error while retaining a server-side traceback."""
    logger.exception("Unhandled API error on path=%s", request.url.path)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "internal server error"},
    )


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


def build_plan_summary(
    total_grid_kwh: float, total_cost_bdt: float, active_directive_types: list[str]
) -> str:
    """Produce a deterministic summary; this is not generated by the LLM."""
    directives = ", ".join(active_directive_types) or "none"
    return (
        "Optimized the 24-hour schedule with deterministic battery and energy "
        f"constraints. Grid import: {total_grid_kwh:.2f} kWh; cost: "
        f"{total_cost_bdt:.2f} BDT; active directives: {directives}."
    )


@app.post("/optimize-energy", response_model=OptimizeEnergyResponse)
def optimize_energy(request: OptimizeEnergyRequest) -> OptimizeEnergyResponse:
    """Interpret notes once, then deterministically optimize and replay the plan."""
    interpreter = GeminiDirectiveInterpreter()
    try:
        interpretation = interpreter.interpret(request)
    except LLMInterpretationError as exc:
        logger.error(
            "Operator-note interpretation failed for scenario_id=%s model=%s reason=%s",
            request.scenario_id,
            getattr(interpreter, "model", "unknown"),
            str(exc),
        )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="operator-note interpretation is unavailable or invalid",
        ) from None

    try:
        solved = optimize_energy_schedule(
            request, interpretation.directive_interpretation
        )
        # Replay independently here as the final endpoint gate; use only replayed
        # totals in the response, never the optimizer's previously calculated totals.
        replayed = validate_solved_plan(
            request,
            interpretation.directive_interpretation,
            solved.hourly_plan,
            solved.total_grid_kwh,
            solved.total_cost_bdt,
            solved.peak_grid_kwh,
        )
    except (OptimizationError, PlanValidationError):
        logger.error("Optimization or plan replay failed for scenario_id=%s", request.scenario_id)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="optimization plan validation failed",
        ) from None

    active_directives = [
        directive.directive_type
        for directive in interpretation.directive_interpretation
        if directive.applies
    ]
    return OptimizeEnergyResponse(
        scenario_id=request.scenario_id,
        directive_interpretation=interpretation.directive_interpretation,
        hourly_plan=solved.hourly_plan,
        total_grid_kwh=replayed.total_grid_kwh,
        total_cost_bdt=replayed.total_cost_bdt,
        peak_grid_kwh=replayed.peak_grid_kwh,
        plan_summary=build_plan_summary(
            replayed.total_grid_kwh,
            replayed.total_cost_bdt,
            active_directives,
        ),
    )
